baseURL = "https://gokhankaraman.com.tr/"
languageCode = "tr-TR"
title = "Haber-G"
theme = "hugo-news"
timeZone = "Europe/Istanbul"
buildFuture = true

[build]
  writeStats = true

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["articles"]
  description = "Dünya, gündem, teknoloji ve yerel gelişmeleri tek yerde takip edin."

[[menu.main]]
  name = "Kategoriler"
  url = "/categories/"
  weight = 1

[[menu.main]]
  name = "Arama"
  url = "/search/"
  weight = 2

[[menu.main]]
  name = "Hakkımızda"
  url = "/hakkimda/"
  weight = 3