baseURL = "https://gokhankaraman.com.tr/"
languageCode = "tr-TR"
title = "Gökhan Karaman Haber"

theme = "hugo-news"

[build]
  writeStats = true

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["articles"]